import { ThemeProvider } from '@/contexts/ThemeProvider'
import './globals.css'
import type { Metadata } from 'next'
import { Toaster } from '@/components/ui/toaster'
import AuthProvider from '@/contexts/SessionProvider'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode
  modal: React.ReactNode
}) {
  return (
    <html className='scroll-smooth m-0 p-0 h-full' lang="en" suppressHydrationWarning={true}>
      <body className=' antialiased h-full'>
        <AuthProvider>
          <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
            {modal}
            {children}
          </ThemeProvider>
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  )
}
